---
layout: home
title: Satoshi 2.0
---

**Open-source tools for _self-custody_, _social recovery_ and _accessible OpSec_.**

- 📜 **Whitepaper** — <https://github.com/voraxanon/whitepaper>  
- 🛟 **Social Recovery** — <https://github.com/voraxanon/social-recovery>  
- 🧪 **Protocol Lab** — <https://github.com/voraxanon/protocol-lab>  

**Donate (BTC):** c1qpyukknh3zqdpwqv7dwn5dqxysc8kt8fsqu80xv
"@ | Set-Content -Path "index.md" -Encoding UTF8

@"
title: Satoshi 2.0
theme: minima
